### ISSUE TITLE
Add "version" command to show the release

### ISSUE THREAD

**Issue by KeisukeYamashita** [armory-io/kayentactl#35]
## What

Like below, I want to know the release by the command:

```console
$ kayentactl version
```

or 

```console
$ kayentactl --version
```

## Why

Because I want to know the current installed kayentactl.

**Comment by ethanfrogers** [comment]
:wave: Hi, thanks for submitting your PR. Sorry for the delayed reply. I've added some feedback to this PR specifically. Would you mind addressing? Once it's addressed, we'll be able to get it merged.

**Comment by KeisukeYamashita** [comment]
Thank you very much for your kind reviews. The PR has merged so I will close this issue. Thanks.
